[workspace]
resolver = "2"
members = [
    "crates/ahpcl",
    "crates/ahpcl-driver",
    "crates/ahpcl-syntax",
    "crates/ahpcl-sema",
    "crates/ahpcl-eval",
    "crates/ahpcl-codegen",
    "crates/ahpcl-runtime",
    "crates/ahpcl-diagnostics",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Tankun Sriket"]

[workspace.dependencies]
ahpcl-diagnostics = { path = "crates/ahpcl-diagnostics" }
ahpcl-syntax = { path = "crates/ahpcl-syntax" }
ahpcl-sema = { path = "crates/ahpcl-sema" }
ahpcl-eval = { path = "crates/ahpcl-eval" }
ahpcl-codegen = { path = "crates/ahpcl-codegen" }
ahpcl-runtime = { path = "crates/ahpcl-runtime" }
ahpcl-driver = { path = "crates/ahpcl-driver" }
unicode-segmentation = "1"
unicode-width = "0.2"
